<?php


namespace App\Validators;



class TimestampDataValidator extends NumberDataValidator
{
    protected static $type = "timestamp";

    function verify($data, $mode = VERIFY_ALL)
    {
        $this->min(0);
        return parent::verify($data); // TODO: Change the autogenerated stub
    }

    function in_the_past()
    {
        return $this->max(time());
    }

    function in_the_future()
    {
        return $this->min(time());
    }

    function is_latest($allowed_error_range = 5)
    {
        $current_timestamp = time();
        return $this->min($current_timestamp - $allowed_error_range)->max($current_timestamp + $allowed_error_range);
    }
}