<?php


namespace Filters;


use App\Http\Request;

class InputFilter extends BaseFilter
{
    public function __call(Request $request)
    {
        return parent::__call($request); // TODO: Change the autogenerated stub
    }
}