<?php


namespace App\Filters;


use App\Exceptions\MethodNotAllowedException;
use App\Http\Request;
use App\Validators\DataValidator;

class MethodFilter extends BaseFilter
{
    protected $validator;

    function __construct($methods)
    {
        if (!is_array($methods)) {
            $methods = [$methods];
        }
        $this->validator = (new DataValidator())->in_array($methods);
    }

    function pass(Request $request)
    {
        if (!$this->validator->verify($request->method, VERIFY_UNTIL_FAIL)) {
            throw new MethodNotAllowedException($request->method);
        }
        return parent::pass($request); // TODO: Change the autogenerated stub
    }
}